/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class AccountCartList200ResponseResult (
  cartsCount: Option[Int] = None,
  carts: Option[Seq[AccountCartList200ResponseResultCartsInner]] = None
) extends ApiModel

