/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class AnalyticsMetric (
  ordersCount: Option[Int] = None,
  itemsSold: Option[Int] = None,
  grossSales: Option[BigDecimal] = None,
  netSales: Option[BigDecimal] = None,
  totalSales: Option[BigDecimal] = None,
  avgOrderValue: Option[BigDecimal] = None,
  discounts: Option[BigDecimal] = None,
  refunds: Option[BigDecimal] = None,
  tax: Option[BigDecimal] = None,
  shipping: Option[BigDecimal] = None,
  fees: Option[BigDecimal] = None,
  currencyId: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

