/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Cart (
  name: Option[String] = None,
  url: Option[String] = None,
  version: Option[String] = None,
  bridgeVersion: Option[String] = None,
  dbPrefix: Option[String] = None,
  storesInfo: Option[Seq[CartStoreInfo]] = None,
  warehouses: Option[Seq[CartWarehouse]] = None,
  shippingZones: Option[Seq[CartShippingZone]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

