/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CartShippingMethod (
  name: Option[String] = None,
  handlingFee: Option[String] = None,
  handlingEnabled: Option[String] = None,
  handlingType: Option[String] = None,
  defaultPrice: Option[String] = None,
  defaultPriceType: Option[String] = None,
  `type`: Option[String] = None,
  enabled: Option[String] = None,
  minOrderAmount: Option[String] = None,
  rates: Option[Seq[CartShippingMethodRate]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

