/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CartStoreInfo (
  storeId: Option[String] = None,
  name: Option[String] = None,
  language: Option[String] = None,
  storeLanguages: Option[Seq[Language]] = None,
  currency: Option[Currency] = None,
  storeCurrencies: Option[Seq[Currency]] = None,
  timezone: Option[String] = None,
  country: Option[String] = None,
  rootCategoryId: Option[String] = None,
  multiStoreUrl: Option[String] = None,
  active: Option[Boolean] = None,
  weightUnit: Option[String] = None,
  dimensionUnit: Option[String] = None,
  pricesIncludeTax: Option[Boolean] = None,
  carrierInfo: Option[Seq[Carrier]] = None,
  storeOwnerInfo: Option[Info] = None,
  defaultWarehouseId: Option[String] = None,
  channels: Option[Seq[CartChannel]] = None,
  pickupLocations: Option[Seq[CartPickupLocation]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

