/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class CatalogPriceRule (
  id: Option[String] = None,
  gid: Option[String] = None,
  `type`: Option[String] = None,
  name: Option[String] = None,
  description: Option[String] = None,
  shortDescription: Option[String] = None,
  avail: Option[Boolean] = None,
  actions: Option[Seq[CatalogPriceRuleAction]] = None,
  createdTime: Option[A2CDateTime] = None,
  dateStart: Option[A2CDateTime] = None,
  dateEnd: Option[A2CDateTime] = None,
  usageCount: Option[BigDecimal] = None,
  conditions: Option[Seq[CouponCondition]] = None,
  usesPerOrderLimit: Option[Int] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

