/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class CatalogPriceRuleAction (
  scope: Option[String] = None,
  applyTo: Option[String] = None,
  `type`: Option[String] = None,
  quantity: Option[BigDecimal] = None,
  value: Option[BigDecimal] = None,
  currencyCode: Option[String] = None,
  includeTax: Option[Boolean] = None,
  conditions: Option[Seq[CouponCondition]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

