/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CategoryAddBatch (
  /* Contains an array of categories objects. The list of properties may vary depending on the specific platform. */
  payload: Seq[CategoryAddBatchPayloadInner]
) extends ApiModel

