/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class Child (
  id: Option[String] = None,
  parentId: Option[String] = None,
  sku: Option[String] = None,
  upc: Option[String] = None,
  ean: Option[String] = None,
  mpn: Option[String] = None,
  gtin: Option[String] = None,
  isbn: Option[String] = None,
  url: Option[String] = None,
  seoUrl: Option[String] = None,
  sortOrder: Option[Int] = None,
  createdTime: Option[A2CDateTime] = None,
  modifiedTime: Option[A2CDateTime] = None,
  name: Option[String] = None,
  shortDescription: Option[String] = None,
  fullDescription: Option[String] = None,
  images: Option[Seq[Image]] = None,
  combination: Option[Seq[ProductChildItemCombination]] = None,
  defaultPrice: Option[BigDecimal] = None,
  costPrice: Option[BigDecimal] = None,
  listPrice: Option[BigDecimal] = None,
  wholesalePrice: Option[BigDecimal] = None,
  advancedPrice: Option[Seq[ProductAdvancedPrice]] = None,
  taxClassId: Option[String] = None,
  availForSale: Option[Boolean] = None,
  allowBackorders: Option[Boolean] = None,
  inStock: Option[Boolean] = None,
  onSale: Option[Boolean] = None,
  manageStock: Option[Boolean] = None,
  inventoryLevel: Option[BigDecimal] = None,
  inventory: Option[Seq[ProductInventory]] = None,
  minQuantity: Option[BigDecimal] = None,
  defaultQtyInPack: Option[BigDecimal] = None,
  isQtyInPackFixed: Option[Boolean] = None,
  weightUnit: Option[String] = None,
  weight: Option[BigDecimal] = None,
  dimensionsUnit: Option[String] = None,
  width: Option[BigDecimal] = None,
  height: Option[BigDecimal] = None,
  length: Option[BigDecimal] = None,
  metaTitle: Option[String] = None,
  metaDescription: Option[String] = None,
  metaKeywords: Option[String] = None,
  discounts: Option[Seq[Discount]] = None,
  isVirtual: Option[Boolean] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

