/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class Currency (
  id: Option[String] = None,
  name: Option[String] = None,
  iso3: Option[String] = None,
  symbolLeft: Option[String] = None,
  symbolRight: Option[String] = None,
  rate: Option[BigDecimal] = None,
  avail: Option[Boolean] = None,
  default: Option[Boolean] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

