/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CustomerUpdateAddressInner (
  /* The ID of the address. */
  addressBookId: Option[String] = None,
  /* Specifies customer's first name in the address book */
  addressBookFirstName: Option[String] = None,
  /* Specifies customer's last name in the address book */
  addressBookLastName: Option[String] = None,
  /* Specifies customer's company name in the address book */
  addressBookCompany: Option[String] = None,
  /* Specifies customer's fax in the address book */
  addressBookFax: Option[String] = None,
  /* Specifies customer's phone number in the address book */
  addressBookPhone: Option[String] = None,
  /* Specifies customer's mobile phone number in the address book */
  addressBookPhoneMobile: Option[String] = None,
  /* Specifies customer's first address in the address book */
  addressBookAddress1: Option[String] = None,
  /* Specifies customer's second address in the address book */
  addressBookAddress2: Option[String] = None,
  /* Specifies customer's city in the address book */
  addressBookCity: Option[String] = None,
  /* ISO code or name of country */
  addressBookCountry: Option[String] = None,
  /* ISO code or name of state. */
  addressBookState: Option[String] = None,
  /* Specifies customer's postcode */
  addressBookPostcode: Option[String] = None,
  /* Add Tax Id */
  addressBookTaxId: Option[String] = None,
  /* The national ID card number of this person, or a unique tax identification number. */
  addressBookIdentificationNumber: Option[String] = None,
  /* Specifies customer's gender */
  addressBookGender: Option[String] = None,
  /* Specifies customer's alias in the address book */
  addressBookAlias: Option[String] = None,
  /* Specifies customer's address type */
  addressBookType: Option[String] = None,
  /* Defines whether the address is used by default */
  addressBookDefault: Option[Boolean] = None
) extends ApiModel

