/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CustomerWishList (
  id: Option[String] = None,
  name: Option[String] = None,
  description: Option[String] = None,
  isPublic: Option[String] = None,
  createdAt: Option[A2CDateTime] = None,
  modifiedAt: Option[A2CDateTime] = None,
  products: Option[Seq[CustomerWishListItem]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

