/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CustomerUpdate (
  /* Entity id */
  id: Option[String] = None,
  /* Customer group_id */
  groupId: Option[String] = None,
  /* Groups that will be assigned to a customer */
  groupIds: Option[String] = None,
  /* Defines the group where the customer */
  group: Option[String] = None,
  /* Defines customer's email */
  email: Option[String] = None,
  /* Defines customer's phone number */
  phone: Option[String] = None,
  /* Defines customer's first name */
  firstName: Option[String] = None,
  /* Defines customer's last name */
  lastName: Option[String] = None,
  /* Defines customer's birthday */
  birthDay: Option[String] = None,
  /* Defines whether the newsletter subscription is available for the user */
  newsLetterSubscription: Option[Boolean] = None,
  /* Defines consents to notifications */
  consents: Option[Seq[CustomerAddConsentsInner]] = None,
  /* Customer tags */
  tags: Option[String] = None,
  /* Defines customer's gender */
  gender: Option[String] = None,
  /* The customer note. */
  note: Option[String] = None,
  /* Defines customer's status */
  status: Option[String] = None,
  /* Store Id */
  storeId: Option[String] = None,
  address: Option[Seq[CustomerUpdateAddressInner]] = None
) extends ApiModel

