/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CustomerAddress (
  id: Option[String] = None,
  `type`: Option[String] = None,
  firstName: Option[String] = None,
  lastName: Option[String] = None,
  postcode: Option[String] = None,
  address1: Option[String] = None,
  address2: Option[String] = None,
  phone: Option[String] = None,
  phoneMobile: Option[String] = None,
  city: Option[String] = None,
  country: Option[Country] = None,
  state: Option[State] = None,
  company: Option[String] = None,
  fax: Option[String] = None,
  website: Option[String] = None,
  gender: Option[String] = None,
  region: Option[String] = None,
  default: Option[Boolean] = None,
  taxId: Option[String] = None,
  identificationNumber: Option[String] = None,
  alias: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

