/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Customer (
  id: Option[String] = None,
  email: Option[String] = None,
  firstName: Option[String] = None,
  lastName: Option[String] = None,
  phone: Option[String] = None,
  createdTime: Option[A2CDateTime] = None,
  modifiedTime: Option[A2CDateTime] = None,
  group: Option[Seq[CustomerGroup]] = None,
  login: Option[String] = None,
  lastLogin: Option[A2CDateTime] = None,
  birthDay: Option[A2CDateTime] = None,
  status: Option[String] = None,
  isGuest: Option[Boolean] = None,
  newsLetterSubscription: Option[Boolean] = None,
  consents: Option[Seq[CustomerConsent]] = None,
  gender: Option[String] = None,
  storesIds: Option[Seq[String]] = None,
  website: Option[String] = None,
  fax: Option[String] = None,
  company: Option[String] = None,
  ipAddress: Option[String] = None,
  addressBook: Option[Seq[CustomerAddress]] = None,
  langId: Option[String] = None,
  ordersCount: Option[Int] = None,
  lastOrderId: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

