/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Image (
  id: Option[String] = None,
  httpPath: Option[String] = None,
  fileName: Option[String] = None,
  mimeType: Option[String] = None,
  size: Option[Int] = None,
  createAt: Option[A2CDateTime] = None,
  modifiedAt: Option[A2CDateTime] = None,
  alt: Option[String] = None,
  avail: Option[Boolean] = None,
  sortOrder: Option[Int] = None,
  `type`: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

