/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class MarketplaceProduct (
  id: Option[String] = None,
  `type`: Option[String] = None,
  uAsin: Option[String] = None,
  uEan: Option[String] = None,
  uGtin: Option[String] = None,
  uIsbn: Option[String] = None,
  uMpn: Option[String] = None,
  uUpc: Option[String] = None,
  name: Option[String] = None,
  description: Option[String] = None,
  url: Option[String] = None,
  price: Option[BigDecimal] = None,
  images: Option[Seq[Image]] = None,
  productOptions: Option[Seq[ProductOption]] = None,
  manufacturer: Option[String] = None,
  brand: Option[String] = None,
  weight: Option[BigDecimal] = None,
  weightUnit: Option[String] = None,
  dimensionsUnit: Option[String] = None,
  width: Option[BigDecimal] = None,
  height: Option[BigDecimal] = None,
  length: Option[BigDecimal] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

