/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ModelReturn (
  id: Option[String] = None,
  name: Option[String] = None,
  orderId: Option[String] = None,
  customerId: Option[String] = None,
  storeId: Option[String] = None,
  createdAt: Option[String] = None,
  modifiedAt: Option[String] = None,
  status: Option[ReturnStatus] = None,
  orderProducts: Option[Seq[ReturnOrderProduct]] = None,
  comment: Option[String] = None,
  staffNote: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

