/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderAbandoned (
  id: Option[String] = None,
  customer: Option[BaseCustomer] = None,
  basketId: Option[String] = None,
  basketUrl: Option[String] = None,
  createdAt: Option[A2CDateTime] = None,
  modifiedAt: Option[A2CDateTime] = None,
  currency: Option[Currency] = None,
  totals: Option[OrderTotals] = None,
  orderProducts: Option[Seq[OrderItem]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

