/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class OrderStatusRefund (
  shipping: Option[BigDecimal] = None,
  fee: Option[BigDecimal] = None,
  tax: Option[BigDecimal] = None,
  totalRefunded: Option[BigDecimal] = None,
  time: Option[A2CDateTime] = None,
  comment: Option[String] = None,
  refundedItems: Option[Seq[OrderStatusRefundItem]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

