/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderCalculateOrderItemInner (
  /* Defines orders specified by order item id */
  orderItemId: String,
  /* Defines orders specified by order item quantity */
  orderItemQuantity: Int,
  /* Ordered product variant. Where x is order item ID */
  orderItemVariantId: Option[String] = None,
  /* Index of the parent grouped/bundle product */
  orderItemParent: Option[Int] = None,
  /* Option name of the parent grouped/bundle product */
  orderItemParentOptionName: Option[String] = None,
  orderItemOption: Option[Seq[OrderCalculateOrderItemInnerOrderItemOptionInner]] = None
) extends ApiModel

