/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Order (
  id: Option[String] = None,
  orderId: Option[String] = None,
  basketId: Option[String] = None,
  channelId: Option[String] = None,
  customer: Option[BaseCustomer] = None,
  createAt: Option[A2CDateTime] = None,
  currency: Option[Currency] = None,
  shippingAddress: Option[CustomerAddress] = None,
  billingAddress: Option[CustomerAddress] = None,
  paymentMethod: Option[OrderPaymentMethod] = None,
  shippingMethod: Option[OrderShippingMethod] = None,
  shippingMethods: Option[Seq[OrderShippingMethod]] = None,
  status: Option[OrderStatus] = None,
  totals: Option[OrderTotals] = None,
  total: Option[OrderTotal] = None,
  discounts: Option[Seq[OrderTotalsNewDiscount]] = None,
  orderProducts: Option[Seq[OrderItem]] = None,
  bundles: Option[Seq[OrderItem]] = None,
  modifiedAt: Option[A2CDateTime] = None,
  finishedTime: Option[A2CDateTime] = None,
  comment: Option[String] = None,
  storeId: Option[String] = None,
  warehousesIds: Option[Seq[String]] = None,
  refunds: Option[Seq[OrderRefund]] = None,
  giftMessage: Option[String] = None,
  orderDetailsUrl: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

