/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderReturnUpdateOrderProductsInner (
  /* Defines which products from the order should be returned */
  orderProductId: String,
  /* Defines how many product units from the order should be returned */
  orderProductQuantity: Int,
  /* Defines product return status */
  orderProductStatus: Option[String] = None,
  /* Defines the ID of the return action */
  orderProductActionId: String
) extends ApiModel

