/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderCalculate (
  /* Defines the customer specified by email for whom the order needs to be calculated */
  customerEmail: String,
  /* Currency Id */
  currencyId: Option[String] = None,
  /* Store Id */
  storeId: Option[String] = None,
  /* Coupons that will be applied to order. If the order isn't eligible for any given discount code or there is no discount with such a code it will be skipped during calculation */
  coupons: Option[Seq[String]] = None,
  /* <p>Specifies the rounding precision for fractional numeric values (such as prices, taxes, and weights).</p> <p>Supported values range from <b>1</b> to <b>6</b>.</p> <p>The default rounding precision may vary depending on the platform. You can retrieve the default value using the <strong>cart.info</strong> method in the <code>default_rounding_precision</code> field. </p><p>Values are rounded to the nearest number at the specified precision. Fractions of .5 or higher are rounded up, while fractions lower than .5 are rounded down.</p> */
  roundingPrecision: Option[Int] = None,
  /* Specifies shipping first name */
  shippFirstName: String,
  /* Specifies shipping last name */
  shippLastName: String,
  /* Specifies first shipping address */
  shippAddress1: String,
  /* Specifies second address line of a shipping street address */
  shippAddress2: Option[String] = None,
  /* Specifies shipping city */
  shippCity: String,
  /* Specifies shipping postcode */
  shippPostcode: String,
  /* Specifies shipping state code */
  shippState: Option[String] = None,
  /* Specifies shipping country code */
  shippCountry: String,
  /* Specifies shipping company */
  shippCompany: Option[String] = None,
  /* Specifies shipping phone */
  shippPhone: Option[String] = None,
  /* Specifies billing first name */
  billFirstName: Option[String] = None,
  /* Specifies billing last name */
  billLastName: Option[String] = None,
  /* Specifies first billing address */
  billAddress1: Option[String] = None,
  /* Specifies second billing address */
  billAddress2: Option[String] = None,
  /* Specifies billing city */
  billCity: Option[String] = None,
  /* Specifies billing postcode */
  billPostcode: Option[String] = None,
  /* Specifies billing state code */
  billState: Option[String] = None,
  /* Specifies billing country code */
  billCountry: Option[String] = None,
  /* Specifies billing company */
  billCompany: Option[String] = None,
  /* Specifies billing phone */
  billPhone: Option[String] = None,
  /* Set this parameter in order to choose which entity fields you want to retrieve */
  responseFields: Option[String] = None,
  orderItem: Seq[OrderCalculateOrderItemInner]
) extends ApiModel

