/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderCalculateOrderItemInnerOrderItemOptionInner (
  /* Ordered Product Option Name. Where x is order item ID, y is order item option ID */
  orderItemOptionName: Option[String] = None,
  /* Ordered product option value Where x is order item ID, y - order item option ID */
  orderItemOptionValue: Option[String] = None
) extends ApiModel

