/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class OrderItemOption (
  optionId: Option[String] = None,
  name: Option[String] = None,
  value: Option[String] = None,
  price: Option[BigDecimal] = None,
  weight: Option[BigDecimal] = None,
  `type`: Option[String] = None,
  productOptionValueId: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

