/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderPreestimateShippingList (
  /* This parameter is used for selecting a warehouse where you need to set/modify a product quantity. */
  warehouseId: Option[String] = None,
  /* Retrieves orders specified by customer id */
  customerId: Option[String] = None,
  /* Retrieves orders specified by customer email */
  customerEmail: Option[String] = None,
  /* Store Id */
  storeId: Option[String] = None,
  /* Specifies first shipping address */
  shippAddress1: Option[String] = None,
  /* Specifies shipping city */
  shippCity: Option[String] = None,
  /* Specifies shipping postcode */
  shippPostcode: Option[String] = None,
  /* Specifies shipping state code */
  shippState: Option[String] = None,
  /* Specifies shipping country code */
  shippCountry: String,
  /* Set this parameter in order to choose which entity fields you want to retrieve */
  params: Option[String] = None,
  /* Set this parameter in order to choose which entity fields you want to ignore. Works only if parameter `params` equal force_all */
  exclude: Option[String] = None,
  orderItem: Seq[OrderPreestimateShippingListOrderItemInner]
) extends ApiModel

