/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderReturnAdd (
  /* Defines the order id */
  orderId: Option[String] = None,
  /* Store Id */
  storeId: Option[String] = None,
  /* Defines return request status */
  returnStatusId: String,
  /* Defines return request action */
  returnActionId: String,
  /* Defines return request reason */
  returnReasonId: String,
  /* Defines return request action */
  returnAction: Option[String] = None,
  /* Defines return request reason */
  returnReason: Option[String] = None,
  /* Boolean, whether or not to add the line items back to the store inventory. */
  itemRestock: Option[Boolean] = None,
  /* Specifies staff note */
  staffNote: Option[String] = None,
  /* Specifies return comment */
  comment: Option[String] = None,
  /* Send notifications to customer after order was created */
  sendNotifications: Option[Boolean] = None,
  /* Defines return reject reason */
  rejectReason: Option[String] = None,
  /* A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong> */
  idempotencyKey: Option[String] = None,
  orderProducts: Seq[OrderReturnAddOrderProductsInner]
) extends ApiModel

