/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderAddOrderItemInnerOrderItemPropertyInner (
  /* Ordered product property name. Where x is order item ID, y is order item property ID */
  orderItemPropertyName: Option[String] = None,
  /* Ordered product property value. Where x is order item ID, y - order item property ID */
  orderItemPropertyValue: Option[String] = None
) extends ApiModel

