/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductPriceUpdate (
  /* Defines the product where the price has to be updated */
  productId: Option[String] = None,
  /* Defines product's group prices */
  groupPrices: Option[Seq[ProductPriceUpdateGroupPricesInner]] = None,
  /* A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong> */
  idempotencyKey: Option[String] = None
) extends ApiModel

