/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class ProductAddPackageDetails (
  measureUnit: Option[String] = None,
  weighUnit: Option[String] = None,
  packageDepth: Option[BigDecimal] = None,
  packageLength: Option[BigDecimal] = None,
  packageWidth: Option[BigDecimal] = None,
  weightMajor: Option[BigDecimal] = None,
  weightMinor: Option[BigDecimal] = None,
  shippingPackage: Option[String] = None
) extends ApiModel

