/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductPriceAdd (
  /* Defines the product to which the price has to be added */
  productId: Option[String] = None,
  /* Defines product's group prices */
  groupPrices: Option[Seq[ProductAddGroupPricesInner]] = None,
  /* Store Id */
  storeId: Option[String] = None
) extends ApiModel

