/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class ProductAddSpecificsInnerBookingDetails (
  location: String,
  `type`: ProductAddSpecificsInnerBookingDetailsEnums.`Type`,
  sessionDuration: Option[Int] = None,
  sessionGap: Option[Int] = None,
  sessionsCount: Int,
  timeStrictValue: BigDecimal,
  timeStrictType: ProductAddSpecificsInnerBookingDetailsEnums.TimeStrictType,
  availabilities: Seq[ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner],
  overrides: Option[Seq[ProductAddSpecificsInnerBookingDetailsOverridesInner]] = None
) extends ApiModel

object ProductAddSpecificsInnerBookingDetailsEnums {

  type `Type` = `Type`.Value
  type TimeStrictType = TimeStrictType.Value
  object `Type` extends Enumeration {
    val Date = Value("date")
    val DateTime = Value("date_time")
  }

  object TimeStrictType extends Enumeration {
    val Days = Value("days")
    val Hours = Value("hours")
    val Minutes = Value("minutes")
  }

}
