/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductVariantPriceAdd (
  /* Defines the variant to which the price has to be added */
  id: Option[String] = None,
  /* Product id */
  productId: Option[String] = None,
  /* Defines variants's group prices */
  groupPrices: Seq[ProductAddGroupPricesInner],
  /* Store Id */
  storeId: Option[String] = None
) extends ApiModel

