/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import org.openapitools.client.core.ApiModel

case class ProductVariantAddBatchPayloadInner (
  productId: String,
  /* A unique combination that contains an array of options and their values, which form a variation. */
  combination: Seq[ProductVariantAddBatchPayloadInnerCombinationInner],
  name: Option[String] = None,
  description: Option[String] = None,
  shortDescription: Option[String] = None,
  sku: String,
  model: Option[String] = None,
  price: Option[BigDecimal] = None,
  oldPrice: Option[BigDecimal] = None,
  costPrice: Option[BigDecimal] = None,
  specialPrice: Option[BigDecimal] = None,
  spriceCreate: Option[String] = None,
  spriceExpire: Option[String] = None,
  advancedPrices: Option[Seq[ProductUpdateBatchPayloadInnerAdvancedPricesInner]] = None,
  metaTitle: Option[BigDecimal] = None,
  metaDescription: Option[BigDecimal] = None,
  metaKeywords: Option[Seq[String]] = None,
  categoriesIds: Option[Seq[String]] = None,
  storesIds: Option[Seq[String]] = None,
  weight: Option[BigDecimal] = None,
  width: Option[BigDecimal] = None,
  height: Option[BigDecimal] = None,
  length: Option[BigDecimal] = None,
  weightUnit: Option[String] = None,
  warehouseId: Option[String] = None,
  quantity: Option[BigDecimal] = None,
  manageStock: Option[Boolean] = None,
  inStock: Option[Boolean] = None,
  storeId: Option[String] = None,
  langId: Option[String] = None,
  taxClassId: Option[String] = None,
  backorderStatus: Option[String] = None,
  status: Option[String] = None,
  visible: Option[String] = None,
  isVirtual: Option[Boolean] = None,
  downloadable: Option[Boolean] = None,
  isDefault: Option[Boolean] = None,
  upc: Option[String] = None,
  isbn: Option[String] = None,
  mpn: Option[String] = None,
  ean: Option[String] = None,
  barcode: Option[String] = None,
  availableForSale: Option[Boolean] = None,
  isFreeShipping: Option[Boolean] = None,
  taxable: Option[Boolean] = None,
  seoUrl: Option[String] = None,
  manufacturerId: Option[String] = None,
  harmonizedSystemCode: Option[String] = None,
  marketplaceItemProperties: Option[Any] = None,
  images: Option[Seq[ProductAddBatchPayloadInnerImagesInner]] = None,
  productImagesIds: Option[Seq[String]] = None,
  relatedProductsIds: Option[Seq[String]] = None,
  upSellProductsIds: Option[Seq[String]] = None,
  crossSellProductsIds: Option[Seq[String]] = None
) extends ApiModel

