/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner (
  /* The starting time of the of available booking slot in 24 hours format. Required if <code>type=date_time</code> */
  from: String,
  /* The ending time of the of available booking slot in 24 hours format. Required if <code>type=date_time</code> */
  to: String
) extends ApiModel

