/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductOptionAdd (
  /* Defines option's name */
  name: String,
  /* Defines option's type that has to be added */
  `type`: ProductOptionAddEnums.`Type`,
  /* Defines product id where the option should be added */
  productId: Option[String] = None,
  /* Defines default option value that has to be added */
  defaultOptionValue: Option[String] = None,
  /* Defines option values that has to be added */
  optionValues: Option[String] = None,
  /* Defines option's description */
  description: Option[String] = None,
  /* Defines whether the option is available */
  avail: Option[Boolean] = None,
  /* Sort number in the list */
  sortOrder: Option[Int] = None,
  /* Defines if the option is required */
  required: Option[Boolean] = None,
  /* An array of option values.</b> */
  values: Option[Seq[ProductOptionAddValuesInner]] = None,
  /* Is cache clear required */
  clearCache: Option[Boolean] = None,
  /* A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong> */
  idempotencyKey: Option[String] = None
) extends ApiModel

object ProductOptionAddEnums {

  type `Type` = `Type`.Value
  object `Type` extends Enumeration {
    val OptionTypeSelect = Value("option_type_select")
    val OptionTypeText = Value("option_type_text")
    val OptionTypeRadio = Value("option_type_radio")
    val OptionTypeCheckbox = Value("option_type_checkbox")
    val OptionTypeTextarea = Value("option_type_textarea")
    val OptionTypeReadonly = Value("option_type_readonly")
    val OptionTypeMultiselect = Value("option_type_multiselect")
    val OptionTypeMulticheckbox = Value("option_type_multicheckbox")
    val OptionTypeFile = Value("option_type_file")
    val OptionTypeDate = Value("option_type_date")
    val OptionTypeDatetime = Value("option_type_datetime")
    val OptionTypeTime = Value("option_type_time")
  }

}
