/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductOption (
  id: Option[String] = None,
  productOptionId: Option[String] = None,
  name: Option[String] = None,
  description: Option[String] = None,
  sortOrder: Option[Int] = None,
  `type`: Option[String] = None,
  required: Option[Boolean] = None,
  available: Option[Boolean] = None,
  usedInCombination: Option[Boolean] = None,
  optionItems: Option[Seq[ProductOptionItem]] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

