/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.math.BigDecimal
import java.net.URI
import org.openapitools.client.core.ApiModel

case class ProductAdd (
  /* Defines product's name that has to be added */
  name: String,
  /* Defines product's model that has to be added */
  model: String,
  /* Defines product's description that has to be added */
  description: String,
  /* Defines product's price that has to be added */
  price: BigDecimal,
  /* Defines product's sku that has to be added */
  sku: Option[String] = None,
  /* Defines short description */
  shortDescription: Option[String] = None,
  /* Defines product's type */
  `type`: Option[String] = None,
  /* Defines product's status */
  status: Option[String] = None,
  /* Set visibility status */
  visible: Option[String] = None,
  /* Defines product add that is specified by category id */
  categoryId: Option[String] = None,
  /* Defines product add that is specified by comma-separated categories id */
  categoriesIds: Option[String] = None,
  /* A categorization for the product */
  productClass: Option[String] = None,
  /* A categorization for the product */
  productType: Option[String] = None,
  /* Defines whether the product is virtual */
  isVirtual: Option[Boolean] = None,
  /* Defines whether the product is downloadable */
  downloadable: Option[Boolean] = None,
  /* If true, it indicates the product as a supply, otherwise it indicates that it is a finished product. */
  isSupply: Option[Boolean] = None,
  /* Specifies the set of visible/invisible products for users */
  availableForView: Option[Boolean] = None,
  /* Specifies the set of visible/invisible products for sale */
  availableForSale: Option[Boolean] = None,
  /* Store Id */
  storeId: Option[String] = None,
  /* Assign product to the stores that is specified by comma-separated stores' id */
  storesIds: Option[String] = None,
  /* Language id */
  langId: Option[String] = None,
  /* Defines product's old price */
  oldPrice: Option[BigDecimal] = None,
  /* Defines product's model that has to be added */
  specialPrice: Option[BigDecimal] = None,
  /* Defines product's sale price */
  wholesalePrice: Option[BigDecimal] = None,
  /* Defines new product's cost price */
  costPrice: Option[BigDecimal] = None,
  /* Specifies product's fixed cost shipping price */
  fixedCostShippingPrice: Option[BigDecimal] = None,
  /* Defines product's tier prices */
  tierPrices: Option[Seq[ProductAddTierPricesInner]] = None,
  /* Defines product's group prices */
  groupPrices: Option[Seq[ProductAddGroupPricesInner]] = None,
  /* Defines buy it now value */
  buyitnowPrice: Option[BigDecimal] = None,
  /* Defines reserve price value */
  reservePrice: Option[BigDecimal] = None,
  /* Defines product's quantity that has to be added */
  quantity: Option[BigDecimal] = None,
  /* Set stock status */
  inStock: Option[Boolean] = None,
  /* Defines inventory tracking for product */
  manageStock: Option[Boolean] = None,
  /* This parameter is used for selecting a warehouse where you need to set/modify a product quantity. */
  warehouseId: Option[String] = None,
  /* Set backorder status */
  backorderStatus: Option[String] = None,
  /* The minimum quantity an order must contain, to be eligible to purchase this product. */
  minOrderQuantity: Option[BigDecimal] = None,
  /* The maximum quantity an order can contain when purchasing the product. */
  maxOrderQuantity: Option[BigDecimal] = None,
  /* Specify the quantity threshold below which the product is considered low in stock */
  lowStockThreshold: Option[BigDecimal] = None,
  /* Weight */
  weight: Option[BigDecimal] = None,
  /* Weight Unit */
  weightUnit: Option[String] = None,
  /* Defines product's width */
  width: Option[BigDecimal] = None,
  /* Defines product's height */
  height: Option[BigDecimal] = None,
  /* Defines product's length */
  length: Option[BigDecimal] = None,
  /* Weight Unit */
  dimensionsUnit: Option[String] = None,
  /* A barcode is a unique code composed of numbers used as a product identifier. */
  barcode: Option[String] = None,
  /* Universal Product Code. A UPC (UPC-A) is a commonly used identifer for many different products. */
  upc: Option[String] = None,
  /* European Article Number. An EAN is a unique 8 or 13-digit identifier that many industries (such as book publishers) use to identify products. */
  ean: Option[String] = None,
  /* International Standard Book Number. An ISBN is a unique identifier for books. */
  isbn: Option[String] = None,
  /* Global Trade Item Number. An GTIN is an identifier for trade items. */
  gtin: Option[String] = None,
  /* Manufacturer Part Number. A MPN is an identifier of a particular part design or material used. */
  mpn: Option[String] = None,
  /* Amazon Standard Identification Number. */
  asin: Option[String] = None,
  /* Groups all variations, that you want to combine into one product. */
  productReference: Option[String] = None,
  /* External product link */
  externalProductLink: Option[String] = None,
  /* Harmonized System Code. An HSC is a 6-digit identifier that allows participating countries to classify traded goods on a common basis for customs purposes */
  harmonizedSystemCode: Option[String] = None,
  /* The country where the inventory item was made */
  countryOfOrigin: Option[String] = None,
  /* Defines product's manufacturer */
  manufacturer: Option[String] = None,
  /* Defines product's manufacturer by manufacturer_id */
  manufacturerId: Option[String] = None,
  manufacturerInfo: Option[ProductAddManufacturerInfo] = None,
  /* Defines product brand name */
  brandName: Option[String] = None,
  /* Image Url */
  imageUrl: Option[String] = None,
  /* Defines image's name */
  imageName: Option[String] = None,
  /* Image Url */
  additionalImageUrls: Option[Seq[URI]] = None,
  /* File Url */
  files: Option[Seq[ProductAddFilesInner]] = None,
  sizeChart: Option[ProductAddSizeChart] = None,
  /* Defines product's related products ids that has to be added */
  relatedProductsIds: Option[String] = None,
  /* Defines product's up-sell products ids that has to be added */
  upSellProductsIds: Option[String] = None,
  /* Defines product's cross-sell products ids that has to be added */
  crossSellProductsIds: Option[String] = None,
  /* Defines product’s attribute set name in Magento */
  attributeSetName: Option[String] = None,
  /* Defines product’s attribute name separated with a comma in Magento */
  attributeName: Option[String] = None,
  /* Defines unique search keywords */
  searchKeywords: Option[String] = None,
  /* Product tags */
  tags: Option[String] = None,
  /* A list of material strings for materials used in the product. */
  materials: Option[Seq[String]] = None,
  /* An array of product certifications. The list of possible certifications can be obtained using the \"<i>category.info</i>\" method (<i>additional_fields->rules->product_certifications</i>). */
  certifications: Option[Seq[ProductAddCertificationsInner]] = None,
  /* An array of Item Specific Name/Value pairs used by the seller to provide descriptive details of an item in a structured manner.         The list of possible specifications can be obtained using the category.info method (additional_fields->product_specifics).         <b>The structure of the parameter is different for specific platforms.</b> */
  specifics: Option[Seq[ProductAddSpecificsInner]] = None,
  /* Allows to schedule a time in the future that the item becomes available. The value should be greater than the current date and time. */
  availFrom: Option[String] = None,
  /* Defines the date of special price creation */
  spriceCreate: Option[String] = None,
  /* Defines the date of special price modification */
  spriceModified: Option[String] = None,
  /* Defines the term of special price offer duration */
  spriceExpire: Option[String] = None,
  /* Defines the date of entity creation */
  createdAt: Option[String] = None,
  /* When true, automatically renews a listing upon its expiration. */
  autoRenew: Option[Boolean] = None,
  /* An enumerated string for the era in which the maker made the product. */
  whenMade: Option[String] = None,
  /* Defines unique meta title for each entity */
  metaTitle: Option[String] = None,
  /* Defines unique meta keywords for each entity */
  metaKeywords: Option[String] = None,
  /* Defines unique meta description of a entity */
  metaDescription: Option[String] = None,
  /* Defines unique product's URL */
  url: Option[String] = None,
  /* Defines unique URL for SEO */
  seoUrl: Option[String] = None,
  /* Defines tax classes where entity has to be added */
  taxClassId: Option[String] = None,
  /* Specifies whether a tax is charged */
  taxable: Option[Boolean] = None,
  salesTax: Option[ProductAddSalesTax] = None,
  /* The human-readable label for the condition (e.g., \"New\"). */
  condition: Option[String] = None,
  /* Detailed description of the product condition. */
  conditionDescription: Option[String] = None,
  /* Flag used to determine whether the product condition is shown to the customer on the product page. */
  allowDisplayCondition: Option[Boolean] = None,
  /* Identifies the payment method (such as PayPal) that the seller will accept when the buyer pays for the item. Look at cart.info method response for allowed values.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">payment_methods[0] = string</br>payment_methods[1] = string</br></code></div></div> */
  paymentMethods: Option[Seq[String]] = None,
  /* Valid PayPal email address for the PayPal account that the seller will use if they offer PayPal as a payment method for the listing. */
  paypalEmail: Option[String] = None,
  /* The numeric ID of the shipping template associated with the products in Etsy. You can find possible values in the \"cart.info\" API method response, in the field shipping_zones[]->id. */
  shippingTemplateId: Option[Int] = None,
  /* The numeric ID of the processing profile (readiness state) for physical products in Etsy. You can find possible values in the \"cart.info\" API method response, in the field processing_profiles[]->readiness_state_id. */
  processingProfileId: Option[Int] = None,
  /* The shipping details, including flat and calculated shipping costs and shipping insurance costs. Look at cart.info method response for allowed values.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">shipping_details[0][<b>shipping_type</b>] = string </br>shipping_details[0][<b>shipping_service</b>] = string</br>shipping_details[0][<b>shipping_cost</b>] = decimal</br>shipping_details[1][<b>shipping_type</b>] = string </br>shipping_details[1][<b>shipping_service</b>] = string</br>shipping_details[1][<b>shipping_cost</b>] = decimal</br></code></div></div> */
  shippingDetails: Option[Seq[ProductAddShippingDetailsInner]] = None,
  /* Specifies product's free shipping flag that has to be added */
  isFreeShipping: Option[Boolean] = None,
  /* The delivery promise that applies to offer */
  deliveryCode: Option[String] = None,
  /* Defines the type of the delivery. */
  deliveryType: Option[String] = None,
  /* Defines delivery time in days. */
  deliveryTime: Option[Int] = None,
  /* Defines delivery options for product by ids. */
  deliveryOptionIds: Option[String] = None,
  packageDetails: Option[ProductAddPackageDetails] = None,
  /* Defines product's logistic channel settings */
  logisticInfo: Option[Seq[ProductAddLogisticInfoInner]] = None,
  /* Describes the number of days the seller wants the listing to be active. Look at cart.info method response for allowed values. */
  listingDuration: Option[String] = None,
  /* Indicates the selling format of the marketplace listing. */
  listingType: Option[String] = None,
  /* Specifies the type of category (e.g., apparel or other) for the product being added. */
  categoryType: Option[String] = None,
  /* Indicates whether the seller allows the buyer to return the item. */
  returnAccepted: Option[Boolean] = None,
  sellerProfiles: Option[ProductAddSellerProfiles] = None,
  /* This allows buyers to remain anonymous when the bid or buy an item. */
  auctionConfidentialityLevel: Option[String] = None,
  bestOffer: Option[ProductAddBestOffer] = None,
  /* Defines product's production partner ids that has to be added */
  productionPartnerIds: Option[String] = None,
  /* String containing the JSON representation of the supplied data */
  marketplaceItemProperties: Option[String] = None,
  /* Is cache clear required */
  clearCache: Option[Boolean] = None,
  /* Specifies the number of product's reviews */
  viewedCount: Option[Int] = None,
  /* Defines how many times the product was ordered */
  orderedCount: Option[Int] = None,
  /* Add Shop Section Id */
  shopSectionId: Option[Int] = None,
  /* Add Return Policy Id */
  returnPolicyId: Option[Int] = None,
  personalizationDetails: Option[ProductAddPersonalizationDetails] = None
) extends ApiModel

