/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductAddSpecificsInner (
  name: Option[String] = None,
  value: Option[String] = None,
  values: Option[Seq[String]] = None,
  usedForVariations: Option[Boolean] = None,
  scaleId: Option[Int] = None,
  inputValue: Option[String] = None,
  foodDetails: Option[ProductAddSpecificsInnerFoodDetails] = None,
  groupProductsDetails: Option[Seq[ProductAddSpecificsInnerGroupProductsDetailsInner]] = None,
  bookingDetails: Option[ProductAddSpecificsInnerBookingDetails] = None
) extends ApiModel

