/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ProductAddManufacturerInfo (
  /* Defines manufacturer`s name */
  name: Option[String] = None,
  /* Defines manufacturer`s address */
  address: Option[String] = None,
  /* Defines manufacturer`s phone */
  phone: Option[String] = None,
  /* Defines manufacturer`s email */
  email: Option[String] = None
) extends ApiModel

