/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class StoreAttribute (
  id: Option[String] = None,
  code: Option[String] = None,
  `type`: Option[String] = None,
  name: Option[String] = None,
  defaultValues: Option[Seq[String]] = None,
  position: Option[Int] = None,
  visible: Option[Boolean] = None,
  required: Option[Boolean] = None,
  system: Option[Boolean] = None,
  values: Option[Seq[String]] = None,
  storeId: Option[String] = None,
  langId: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

