/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Subscriber (
  id: Option[String] = None,
  customerId: Option[String] = None,
  email: Option[String] = None,
  subscribed: Option[Boolean] = None,
  firstName: Option[String] = None,
  lastName: Option[String] = None,
  storesIds: Option[Seq[String]] = None,
  createdTime: Option[String] = None,
  modifiedTime: Option[String] = None,
  langId: Option[String] = None,
  gender: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

