/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Webhook (
  id: Option[Int] = None,
  label: Option[String] = None,
  storeId: Option[String] = None,
  langId: Option[String] = None,
  active: Option[Boolean] = None,
  callback: Option[String] = None,
  fields: Option[String] = None,
  responseFields: Option[String] = None,
  createdAt: Option[String] = None,
  updatedAt: Option[String] = None,
  entity: Option[String] = None,
  action: Option[String] = None,
  additionalFields: Option[Any] = None,
  customFields: Option[Any] = None
) extends ApiModel

