/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model._
import org.json4s._
import scala.reflect.ClassTag

object EnumsSerializers {

  def all: Seq[Serializer[_]] = Seq[Serializer[_]]() :+
    new EnumNameSerializer(AccountCartAddEnums.CartId) :+
    new EnumNameSerializer(CartCouponAddEnums.ActionType) :+
    new EnumNameSerializer(CartCouponAddEnums.ActionApplyTo) :+
    new EnumNameSerializer(CartCouponAddEnums.ActionScope) :+
    new EnumNameSerializer(CustomerAddConsentsInnerEnums.`Type`) :+
    new EnumNameSerializer(ProductAddBatchEnums.NestedItemsUpdateBehaviour) :+
    new EnumNameSerializer(ProductAddSpecificsInnerBookingDetailsEnums.`Type`) :+
    new EnumNameSerializer(ProductAddSpecificsInnerBookingDetailsEnums.TimeStrictType) :+
    new EnumNameSerializer(ProductAddSpecificsInnerBookingDetailsAvailabilitiesInnerEnums.Day) :+
    new EnumNameSerializer(ProductAddSpecificsInnerBookingDetailsOverridesInnerEnums.Day) :+
    new EnumNameSerializer(ProductImageAddEnums.`Type`) :+
    new EnumNameSerializer(ProductOptionAddEnums.`Type`) :+
    new EnumNameSerializer(ProductUpdateBatchEnums.NestedItemsUpdateBehaviour) :+
    new EnumNameSerializer(ProductVariantImageAddEnums.`Type`) :+
    new EnumNameSerializer(ProductVariantUpdateBatchEnums.NestedItemsUpdateBehaviour)

  private class EnumNameSerializer[E <: Enumeration: ClassTag](enum: E)
    extends Serializer[E#Value] {
    import JsonDSL._

    val EnumerationClass: Class[E#Value] = classOf[E#Value]

    def deserialize(implicit format: Formats):
    PartialFunction[(TypeInfo, JValue), E#Value] = {
      case (t @ TypeInfo(EnumerationClass, _), json) if isValid(json) =>
        json match {
          case JString(value) =>
            enum.withName(value)
          case value =>
            throw new MappingException(s"Can't convert $value to $EnumerationClass")
        }
    }

    private[this] def isValid(json: JValue) = json match {
      case JString(value) if enum.values.exists(_.toString == value) => true
      case _ => false
    }

    def serialize(implicit format: Formats): PartialFunction[Any, JValue] = {
      case i: E#Value => i.toString
    }
  }

}
